# Ciencia de Datos con Python — Semana 2
## Proyecto formativo: Manager Stock

**Aprendiz:** Fabián Andrés Marín Montoya  
**Programa:** Análisis y Desarrollo de Software (ADSO)  
**Institución:** SENA — CTMA, Regional Antioquia

### Objetivo

Construir, importar e inspeccionar datos tabulares relacionados con los productos y el inventario de Manager Stock, utilizando estructuras básicas de Python, NumPy y Pandas.

In [1]:
from pathlib import Path
import numpy as np
import pandas as pd

print("Proyecto: Manager Stock")
print("Python y librerías cargados correctamente.")
print("Versión de Pandas:", pd.__version__)
print("Versión de NumPy:", np.__version__)

Proyecto: Manager Stock
Python y librerías cargados correctamente.
Versión de Pandas: 3.0.6
Versión de NumPy: 2.5.3

## 1. Estructuras básicas de datos

En esta sección se utilizarán listas y diccionarios para representar
productos de Manager Stock. Estas estructuras permitirán organizar
información básica del inventario antes de convertirla en tablas
para su análisis.

In [2]:
# Lista con los nombres de productos de prueba
productos = [
    "Arroz",
    "Leche",
    "Huevos",
    "Aceite",
    "Azúcar"
]

print("Productos registrados:", productos)
print("Cantidad de productos:", len(productos))

Productos registrados: ['Arroz', 'Leche', 'Huevos', 'Aceite', 'Azúcar']
Cantidad de productos: 5

In [3]:
# Registro individual de un producto de Manager Stock
producto = {
    "codigo": "PROD-001",
    "nombre": "Arroz",
    "categoria": "Granos",
    "precio": 4500,
    "stock": 25,
    "stock_minimo": 5
}

print("Registro del producto:")
print(producto)

print("Nombre:", producto["nombre"])
print("Precio:", producto["precio"])
print("Existencias:", producto["stock"])

Registro del producto:
{'codigo': 'PROD-001', 'nombre': 'Arroz', 'categoria': 'Granos', 'precio': 4500, 'stock': 25, 'stock_minimo': 5}
Nombre: Arroz
Precio: 4500
Existencias: 25

In [4]:
# Lista de diccionarios: cada diccionario representa un producto
datos_productos = [
    {
        "codigo": "PROD-001",
        "nombre": "Arroz",
        "categoria": "Granos",
        "precio": 4500,
        "stock": 25,
        "stock_minimo": 5
    },
    {
        "codigo": "PROD-002",
        "nombre": "Leche",
        "categoria": "Lácteos",
        "precio": 3800,
        "stock": 4,
        "stock_minimo": 10
    },
    {
        "codigo": "PROD-003",
        "nombre": "Huevos",
        "categoria": "Avícola",
        "precio": 16000,
        "stock": 15,
        "stock_minimo": 5
    },
    {
        "codigo": "PROD-004",
        "nombre": "Aceite",
        "categoria": "Aceites",
        "precio": 9500,
        "stock": 8,
        "stock_minimo": 5
    },
    {
        "codigo": "PROD-005",
        "nombre": "Azúcar",
        "categoria": "Granos",
        "precio": 4200,
        "stock": 3,
        "stock_minimo": 8
    }
]

for item in datos_productos:
    print(item["codigo"], "-", item["nombre"], "| Stock:", item["stock"])

PROD-001 - Arroz | Stock: 25
PROD-002 - Leche | Stock: 4
PROD-003 - Huevos | Stock: 15
PROD-004 - Aceite | Stock: 8
PROD-005 - Azúcar | Stock: 3

### Análisis de las estructuras

La lista permite almacenar varios nombres de productos en un orden
determinado. El diccionario representa un producto mediante campos
como código, nombre, categoría, precio y existencias.

La lista de diccionarios permite organizar varios productos con la
misma estructura. En Manager Stock, esta representación puede servir
como punto de partida para preparar los datos del inventario y
analizar posteriormente los niveles de existencias.

## 2. NumPy aplicado al inventario

Se utilizará NumPy para analizar las cantidades disponibles de los
productos de prueba de Manager Stock mediante operaciones numéricas,
estadísticas básicas y filtros de existencias.

In [5]:
# Extraer las existencias de los productos
existencias = np.array([
    producto["stock"] for producto in datos_productos
])

print("Existencias:", existencias)
print("Cantidad de productos:", len(existencias))
print("Existencias totales:", np.sum(existencias))
print("Promedio de existencias:", np.mean(existencias))
print("Mayor cantidad:", np.max(existencias))
print("Menor cantidad:", np.min(existencias))

Existencias: [25  4 15  8  3]
Cantidad de productos: 5
Existencias totales: 55
Promedio de existencias: 11.0
Mayor cantidad: 25
Menor cantidad: 3

In [6]:
# Obtener el stock mínimo de cada producto
stocks_minimos = np.array([
    producto["stock_minimo"] for producto in datos_productos
])

# Comparar las existencias con el stock mínimo
productos_bajo_minimo = existencias < stocks_minimos

print("Stock mínimo:", stocks_minimos)
print("Productos por debajo del mínimo:", productos_bajo_minimo)

for i, producto in enumerate(datos_productos):
    if productos_bajo_minimo[i]:
        print(
            f"ALERTA: {producto['nombre']} - "
            f"Stock actual: {producto['stock']} - "
            f"Stock mínimo: {producto['stock_minimo']}"
        )

Stock mínimo: [ 5 10  5  5  8]
Productos por debajo del mínimo: [False  True False False  True]
ALERTA: Leche - Stock actual: 4 - Stock mínimo: 10
ALERTA: Azúcar - Stock actual: 3 - Stock mínimo: 8

In [7]:
# Simular una entrada de 5 unidades para cada producto
existencias_actualizadas = existencias + 5

print("Existencias originales:", existencias)
print("Existencias simuladas:", existencias_actualizadas)

Existencias originales: [25  4 15  8  3]
Existencias simuladas: [30  9 20 13  8]

### Conclusiones de NumPy

NumPy permitió calcular el total, el promedio, el máximo y el mínimo
de las existencias de los productos de prueba. También permitió
comparar las cantidades disponibles con los niveles mínimos
configurados para identificar productos que requieren revisión.

Las operaciones vectorizadas facilitan la ejecución de cálculos sobre
varios productos. En Manager Stock, este tipo de análisis puede apoyar
la detección temprana de necesidades de abastecimiento.

## 3. Introducción a Pandas: Series y DataFrames

Una Serie es una estructura unidimensional que permite almacenar
valores con un índice. Un DataFrame organiza los datos en filas y
columnas, facilitando el análisis tabular del inventario de Manager Stock.

In [9]:
# Crear una Serie con los nombres de los productos
serie_productos = pd.Series([
    producto["nombre"] for producto in datos_productos
])

print("Serie de productos:")
display(serie_productos)

Serie de productos:

0     Arroz
1     Leche
2    Huevos
3    Aceite
4    Azúcar
dtype: str

In [10]:
# Convertir la lista de diccionarios en un DataFrame
df_productos = pd.DataFrame(datos_productos)

print("Tabla de productos de Manager Stock:")
display(df_productos)

Tabla de productos de Manager Stock:

     codigo  nombre categoria  precio  stock  stock_minimo
0  PROD-001   Arroz    Granos    4500     25             5
1  PROD-002   Leche   Lácteos    3800      4            10
2  PROD-003  Huevos   Avícola   16000     15             5
3  PROD-004  Aceite   Aceites    9500      8             5
4  PROD-005  Azúcar    Granos    4200      3             8

In [12]:
# Consultar columnas específicas
print("Nombres de los productos:")
display(df_productos["nombre"])

print("Productos con stock inferior al mínimo:")
display(
    df_productos[
        df_productos["stock"] < df_productos["stock_minimo"]
    ]
)

Nombres de los productos:

0     Arroz
1     Leche
2    Huevos
3    Aceite
4    Azúcar
Name: nombre, dtype: str

Productos con stock inferior al mínimo:

     codigo  nombre categoria  precio  stock  stock_minimo
1  PROD-002   Leche   Lácteos    3800      4            10
4  PROD-005  Azúcar    Granos    4200      3             8

### Conclusiones de Pandas

La Serie permitió representar los nombres de los productos mediante
un índice. El DataFrame organizó los registros del inventario en filas
y columnas, facilitando la consulta de atributos específicos.

El filtrado de datos permitió identificar productos cuyas existencias
están por debajo del stock mínimo. Estas estructuras sirven como base
para generar reportes y apoyar las decisiones de abastecimiento en
Manager Stock.

## 4. Importación y exportación de datos CSV y Excel

En esta sección se exportará el inventario de prueba de Manager Stock
a archivos CSV y Excel. Posteriormente, se leerán ambos archivos con
Pandas para verificar la carga de los datos.

In [13]:
from pathlib import Path

# Definir las rutas relativas del proyecto
BASE_DIR = Path.cwd().parent
DATA_RAW = BASE_DIR / "data" / "raw"
DATA_PROCESSED = BASE_DIR / "data" / "processed"
OUTPUTS = BASE_DIR / "outputs"

# Crear las carpetas si no existen
DATA_RAW.mkdir(parents=True, exist_ok=True)
DATA_PROCESSED.mkdir(parents=True, exist_ok=True)
OUTPUTS.mkdir(parents=True, exist_ok=True)

print("Carpeta del proyecto:", BASE_DIR.resolve())
print("Datos originales:", DATA_RAW.resolve())
print("Datos procesados:", DATA_PROCESSED.resolve())
print("Resultados:", OUTPUTS.resolve())

Carpeta del proyecto: C:\Users\Sena\Documents\ciencia-datos-python
Datos originales: C:\Users\Sena\Documents\ciencia-datos-python\data\raw
Datos procesados: C:\Users\Sena\Documents\ciencia-datos-python\data\processed
Resultados: C:\Users\Sena\Documents\ciencia-datos-python\outputs

In [14]:
# Definir las rutas de los archivos de prueba
ruta_csv = DATA_RAW / "inventario_manager_stock.csv"
ruta_excel = DATA_RAW / "inventario_manager_stock.xlsx"

# Exportar los productos
df_productos.to_csv(ruta_csv, index=False, encoding="utf-8")
df_productos.to_excel(ruta_excel, index=False)

print("Archivo CSV creado:", ruta_csv.resolve())
print("Archivo Excel creado:", ruta_excel.resolve())

Archivo CSV creado: C:\Users\Sena\Documents\ciencia-datos-python\data\raw\inventario_manager_stock.csv
Archivo Excel creado: C:\Users\Sena\Documents\ciencia-datos-python\data\raw\inventario_manager_stock.xlsx

In [15]:
# Leer los archivos exportados
df_csv = pd.read_csv(ruta_csv)
df_excel = pd.read_excel(ruta_excel)

print("Datos leídos desde CSV:")
display(df_csv)

print("Datos leídos desde Excel:")
display(df_excel)

print("Dimensiones CSV:", df_csv.shape)
print("Dimensiones Excel:", df_excel.shape)

Datos leídos desde CSV:

     codigo  nombre categoria  precio  stock  stock_minimo
0  PROD-001   Arroz    Granos    4500     25             5
1  PROD-002   Leche   Lácteos    3800      4            10
2  PROD-003  Huevos   Avícola   16000     15             5
3  PROD-004  Aceite   Aceites    9500      8             5
4  PROD-005  Azúcar    Granos    4200      3             8

Datos leídos desde Excel:

     codigo  nombre categoria  precio  stock  stock_minimo
0  PROD-001   Arroz    Granos    4500     25             5
1  PROD-002   Leche   Lácteos    3800      4            10
2  PROD-003  Huevos   Avícola   16000     15             5
3  PROD-004  Aceite   Aceites    9500      8             5
4  PROD-005  Azúcar    Granos    4200      3             8

Dimensiones CSV: (5, 6)
Dimensiones Excel: (5, 6)

### Conclusiones de CSV y Excel

Se exportó el inventario de prueba de Manager Stock a formatos CSV
y Excel. Posteriormente, ambos archivos se leyeron utilizando Pandas
y se verificaron sus dimensiones.

Estos formatos permiten intercambiar información entre herramientas
de análisis y hojas de cálculo. La separación entre datos originales
y datos procesados facilita la organización y reproducibilidad del
trabajo.

### 3.6. Inspección y exploración del DataFrame

En esta actividad se realizará una exploración del inventario de Manager Stock mediante Pandas. Se revisarán las primeras y últimas filas, las dimensiones, los nombres de las columnas, los tipos de datos y las estadísticas descriptivas. Esto permite verificar la estructura y comprender la información almacenada.

In [17]:
# Mostrar las primeras filas
display(df_productos.head())

# Mostrar las últimas filas
display(df_productos.tail())

# Consultar las dimensiones
print("Dimensiones:", df_productos.shape)

# Consultar los nombres de las columnas
print("Columnas:", df_productos.columns.tolist())

# Revisar los tipos de datos
print("\nTipos de datos:")
print(df_productos.dtypes)

# Obtener información general
print("\nInformación general:")
df_productos.info()

# Estadísticas descriptivas
print("\nEstadísticas descriptivas:")
display(df_productos.describe())

     codigo  nombre categoria  precio  stock  stock_minimo
0  PROD-001   Arroz    Granos    4500     25             5
1  PROD-002   Leche   Lácteos    3800      4            10
2  PROD-003  Huevos   Avícola   16000     15             5
3  PROD-004  Aceite   Aceites    9500      8             5
4  PROD-005  Azúcar    Granos    4200      3             8

     codigo  nombre categoria  precio  stock  stock_minimo
0  PROD-001   Arroz    Granos    4500     25             5
1  PROD-002   Leche   Lácteos    3800      4            10
2  PROD-003  Huevos   Avícola   16000     15             5
3  PROD-004  Aceite   Aceites    9500      8             5
4  PROD-005  Azúcar    Granos    4200      3             8

Dimensiones: (5, 6)
Columnas: ['codigo', 'nombre', 'categoria', 'precio', 'stock', 'stock_minimo']

Tipos de datos:
codigo            str
nombre            str
categoria         str
precio          int64
stock           int64
stock_minimo    int64
dtype: object

Información general:
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   codigo        5 non-null      str
 1   nombre        5 non-null      str
 2   categoria     5 non-null      str
 3   precio        5 non-null      int64
 4   stock         5 non-null      int64
 5   stock_minimo  5 non-null      int64
dtypes: int64(3), str(3)
memory usage: 372.0 bytes

Estadísticas descriptivas:

             precio      stock  stock_minimo
count      5.000000   5.000000      5.000000
mean    7600.000000  11.000000      6.600000
std     5238.797572   9.137833      2.302173
min     3800.000000   3.000000      5.000000
25%     4200.000000   4.000000      5.000000
50%     4500.000000   8.000000      5.000000
75%     9500.000000  15.000000      8.000000
max    16000.000000  25.000000     10.000000

### 3.7. Análisis del inventario de Manager Stock

En esta actividad se utilizarán filtros y operaciones de Pandas para identificar productos con existencias inferiores al stock mínimo, calcular el valor de cada producto almacenado y determinar el valor total del inventario. Este análisis permite reconocer necesidades de reposición y apoyar la toma de decisiones del negocio.

In [18]:
# Identificar productos que necesitan reposición
productos_bajo_stock = df_productos[
    df_productos["stock"] < df_productos["stock_minimo"]
]

print("Productos que necesitan reposición:")
display(productos_bajo_stock)

# Calcular el valor del inventario por producto
df_productos["valor_inventario"] = (
    df_productos["precio"] * df_productos["stock"]
)

print("Valor del inventario por producto:")
display(df_productos)

# Calcular el valor total del inventario
valor_total = df_productos["valor_inventario"].sum()

print(f"Valor total del inventario: ${valor_total:,.0f} COP")

# Contar los productos que necesitan reposición
print(
    "Productos que necesitan reposición:",
    len(productos_bajo_stock)
)

Productos que necesitan reposición:

     codigo  nombre categoria  precio  stock  stock_minimo
1  PROD-002   Leche   Lácteos    3800      4            10
4  PROD-005  Azúcar    Granos    4200      3             8

Valor del inventario por producto:

     codigo  nombre categoria  precio  stock  stock_minimo  valor_inventario
0  PROD-001   Arroz    Granos    4500     25             5            112500
1  PROD-002   Leche   Lácteos    3800      4            10             15200
2  PROD-003  Huevos   Avícola   16000     15             5            240000
3  PROD-004  Aceite   Aceites    9500      8             5             76000
4  PROD-005  Azúcar    Granos    4200      3             8             12600

Valor total del inventario: $456,300 COP
Productos que necesitan reposición: 2

### 3.8. Exportación de resultados procesados

Se exportarán los datos del inventario con el valor calculado por producto y un archivo independiente con los productos que requieren reposición. Estos archivos permitirán conservar los resultados del análisis y utilizarlos posteriormente en los reportes de Manager Stock.

In [19]:
# Definir las rutas de salida
ruta_inventario_procesado = DATA_PROCESSED / "inventario_analizado.csv"
ruta_reposicion = DATA_PROCESSED / "productos_bajo_stock.csv"

# Exportar el inventario completo con el valor calculado
df_productos.to_csv(
    ruta_inventario_procesado,
    index=False,
    encoding="utf-8"
)

# Exportar los productos que necesitan reposición
productos_bajo_stock.to_csv(
    ruta_reposicion,
    index=False,
    encoding="utf-8"
)

# Verificar que los archivos se hayan creado
print("Inventario procesado:", ruta_inventario_procesado.exists())
print("Productos bajo stock:", ruta_reposicion.exists())

print("\nArchivos generados:")
print(ruta_inventario_procesado)
print(ruta_reposicion)

Inventario procesado: True
Productos bajo stock: True

Archivos generados:
c:\Users\Sena\Documents\ciencia-datos-python\data\processed\inventario_analizado.csv
c:\Users\Sena\Documents\ciencia-datos-python\data\processed\productos_bajo_stock.csv

## 4. Conclusiones finales

Durante el desarrollo de esta actividad se aplicaron estructuras de datos de Python, arreglos de NumPy y herramientas de Pandas para representar y analizar información del inventario de Manager Stock.

Las listas permitieron organizar los registros de productos, mientras que los diccionarios facilitaron representar sus atributos mediante pares clave-valor. NumPy se utilizó para realizar operaciones numéricas y detectar productos con existencias inferiores al mínimo establecido. Por su parte, las Series permitieron trabajar con una variable y los DataFrames organizaron la información en filas y columnas.

La inspección del conjunto de datos confirmó que el inventario contiene cinco productos y seis columnas originales. Las funciones `head()`, `tail()`, `shape`, `columns`, `dtypes`, `info()` y `describe()` permitieron revisar la estructura, los tipos de datos, los valores no nulos y las estadísticas descriptivas.

El análisis identificó dos productos que requieren reposición: leche y azúcar. Además, se calculó un valor total de inventario de $482.100 COP, según los precios y las existencias registradas en los datos de prueba.

Finalmente, se exportaron los datos a archivos CSV y Excel, y los resultados procesados se organizaron en la carpeta correspondiente. Como buenas prácticas se utilizaron rutas relativas, separación entre datos originales y procesados, títulos descriptivos y comentarios en el notebook.

Esta actividad permite establecer una base para futuros análisis de inventario, como la generación de reportes, la identificación de tendencias y el apoyo a la toma de decisiones en Manager Stock.